### ISSUE TITLE
Small suggestion: Can we use the full name "Home Assistant" rather than the abbreviation "HASS"?

### ISSUE THREAD

**Issue by konikvranik** [konikvranik/home-assistant#30]
In homeassistant/components/hdmi_cec.py:

  
    loop = (
        # Create own thread if more than 1 CPU
        hass.loop if multiprocessing.cpu_count() < 2 else None)
    host = base_config[DOMAIN].get(CONF_HOST, None)
    if host:
        adapter = TcpAdapter(host, name="HASS", activate_source=False)

Small suggestion: Can we use the full name "Home Assistant" rather than the abbreviation "HASS"?

**Comment by konikvranik** [comment]
Allow to override default name in configuration.

**Comment by konikvranik** [comment]
@armills: We are limited to 13 chars here due to libcec type length.

**Comment by armills** [comment]
Ah, that's a shame. Never mind then.

**Comment by konikvranik** [comment]
@armills: Current solution is to allow user to set custom string in config, but it is shortened to max 13 chars. Default when not set in config is "HomeAssistant".
